// <auto-generated />
using KotasProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KotasProject.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("KotasProject.Models.Abilities", b =>
                {
                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("KotasProject.Models.Ability", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("KotasProject.Models.Pokemon", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainerId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("KotasProject.Models.PokemonTrainer", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId", "TrainerId");

                    b.ToTable("PokemonTrainer");
                });

            modelBuilder.Entity("KotasProject.Models.Sprites", b =>
                {
                    b.Property<string>("Front_Default")
                        .HasColumnType("TEXT");

                    b.ToTable("Sprites");
                });

            modelBuilder.Entity("KotasProject.Models.Trainer.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
